name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Pacman stilinde SVG üreten Platane/snk yapılandırması
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/pacman-contribution-graph.svg?palette=pacman
            dist/pacman-contribution-graph-dark.svg?palette=pacman&color_snake=#ff0000

      # Üretilen görselleri pacman-output branch'ine aktarır
      - name: push pacman SVGs to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: pacman-output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}${{ secrets.GITHUB_TOKEN }}
